spring:
    application:
        name: employeeportal

    datasource:
        url: jdbc:postgresql://localhost:5432/employee_portal
        username: anmol
        password: password
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

server:
    port: 8080